// Code will regenerated by gorm.io/gen.

package dao

import (
	"gorm.io/gen"
	"gorm.io/gorm"
)

type Query struct {
	db *gorm.DB
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db: db,
	}
}
